[general]
import = ["~/config_file/color/vague.toml"]
# [colors.primary]
# background = "#000000"

[font]
size = 18.0
normal = { family = "FiraCode" }

[cursor.style]
shape = "Beam"
blinking = "On"

[window]
startup_mode = "Fullscreen"
# opacity = 0.5

[terminal]
shell = "/bin/zsh"
